# Generated by Django 4.1.7 on 2023-08-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'permissions': [('view_secure_object', 'Can view the object'), ('change_secure_object', 'Can change the object'), ('delete_secure_object', 'Can delete the object')],
            },
        ),
    ]
